### PR TITLE
Diargram search (#1235)

### PR DESCRIPTION
**Pull request by pavelpykhtin**
Implemented search for views and nodes in current view with @mantine/spotlight component.

Please, check that I've covered all export scenarios (static site, webcomponent etc.). I suspect that I could miss something.

### CODE REVIEW

**Comment by Cyclonit** [comment]
Hi @pavelpykhtin,

I am not a contributor/maintainer myself, but I gave it a try and like it a lot. I didn't find any problems in the VS Code extension at least.

What do you think about adding a search button to the TopLeftPanel, that opens the Spotlight? Something like this could do. I am very new to React and didn't find a way of including the shortcut in the tooltip (besides hardcoding it in two places). That would be the cherry on top.

```html
<Tooltip label="Search">
  <ActionIcon
    onClick={() => openSpotlight()}>
    <IconSearch />
  </ActionIcon>
</Tooltip>
```

**Comment by Cyclonit** [comment]
Another improvement would be to include the part of the element that matches the search query in the `Action`. When the query matches anything other than the title/label (e.g. a tag), it is not clear why it shows up in the results. Maybe it'd be possible to include a short dynamic hint after/below the action title, that shows why the action is being shown.

Maybe like this
grafik

**Comment by Cyclonit** [comment]
I prepared a little sample based on your work here: https://github.com/likec4/likec4/compare/feat/diagram-search...Cyclonit:likec4:feat/diagram-search. What do you think about it?

**Comment by davydkov** [comment]
> I prepared a little sample based on your work here: [feat/diagram-search...Cyclonit:likec4:feat/diagram-search](https://github.com/likec4/likec4/compare/feat/diagram-search...Cyclonit:likec4:feat/diagram-search). What do you think about it?

Hey @Cyclonit 
I like the idea!
Can you check this https://mantine.dev/core/highlight/?
Seems a perfect fit

**Comment by davydkov** [comment]
@pavelpykhtin Nice one! Thank you!

**Pull request merged**
